
defaults: &defaults
  adapter: postgres

development:
  database: mis_dev
  host: localhost
  username: mis
  password: mis
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #     repo2:
  #     ...

test: &test
  database: mis_test
  username: mis
  password: mis
  <<: *defaults


production: &production
  database: mis_production
  username: mis		
  password: mis
  host: localhost
  
  <<: *defaults


